name: mar
channels:
  - pytorch
  - defaults
  - nvidia
dependencies:
  - python=3.8.5
  - pip=20.3
  - pytorch-cuda=11.8
  - pytorch=2.2.2
  - torchvision=0.17.2
  - numpy=1.22
  - pip:
    - opencv-python==4.1.2.30
    - opencv-python-headless
    - timm==0.9.12
    - tensorboard==2.10.0
    - scipy==1.9.1
    - gdown==5.2.0
    - pandas==2.0.3
    - matplotlib==3.7.5
    - einops==0.7.0
    - huggingface-hub>=0.26.2
    - transformers
    - diffusers
    - SentencePiece
    - wandb
    - -e git+https://github.com/LTH14/torch-fidelity.git@master#egg=torch-fidelity

#git clone https://github.com/LTH14/torch-fidelity.git
#cd torch-fidelity
#git checkout master
#pip install -e .




